name: 'Chromatic Deployment'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: npm install
        
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # 👇 Chromatic will automatically determine which stories have changed
          # and only run those tests. This is why we use `fetch-depth: 0` above.
          exitZeroOnChanges: true 